2019-10-29 20:53:02,158 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 84, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 20:54:27,620 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-29 20:54:29,414 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 84, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 20:55:32,744 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-29 20:55:59,134 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 85, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 20:57:34,537 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-29 20:57:36,520 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 85, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 20:57:48,309 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 85, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 21:01:32,134 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-29 21:01:34,851 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 85, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 21:05:35,380 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-29 21:05:37,768 ERROR: Exception on /weekly_reflection [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 85, in weekly_reflection
    form = ReflectionForm()
NameError: name 'ReflectionForm' is not defined
2019-10-29 21:06:26,888 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
